# Generated by Django 4.1.2 on 2023-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Дата')),
                ('text_rus', models.TextField(db_column='Текст на рускком')),
                ('text_eng', models.TextField(db_column='Текст на английском')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_column='Created')),
            ],
        ),
    ]
