# Generated by Django 4.1.2 on 2023-04-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(default='None', null=True)),
                ('owner', models.CharField(default='-', max_length=255, null='True')),
                ('author', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(default='-', max_length=255, null=True)),
                ('major', models.CharField(default='-', max_length=255, null=True)),
                ('genre', models.CharField(default='-', max_length=255, null=True)),
                ('domain', models.CharField(default='-', max_length=255, null=True)),
                ('university', models.CharField(default='-', max_length=255, null=True)),
                ('student_code', models.IntegerField(default=0, null=True)),
                ('university_code', models.IntegerField(default=0, null=True)),
                ('date_1', models.IntegerField(default=1900, null=True)),
                ('date_2', models.IntegerField(default=1900, null=True)),
                ('course', models.CharField(default='-', max_length=255, null=True)),
                ('is_marked', models.BooleanField(null=True)),
                ('is_checked', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(default='-', max_length=255, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id', to='annotate.document')),
            ],
        ),
    ]
