# Generated by Django 4.1.2 on 2023-04-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.IntegerField(default=60, null='True'),
        ),
    ]
