# Generated by Django 4.1.2 on 2023-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_alter_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_checked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_marked',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
